name: .NET Tests with Coverage

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      dotnetcore-version:
        description: 'dotnet core version to be installed'
        required: false
        default: '6.0.422'
        type: choice
        options:
          - 6.0.422
          - 8.0.300
      solution_path:
        description: 'Path to the solution (.sln) file'
        required: false
        default: 'HelloWorldSolution.sln'
      build_configuration:
        description: 'Build configuration'
        required: false
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release
      runtime:
        description: 'Runtime Identifier for self-contained deployment'
        required: false
        type: choice
        options:
          - linux-x64
          - win-x64
          - osx-x64
      packaging_type:
        description: 'Packaging type for the application or library'
        required: false
        default: 'framework-dependent'
        type: choice
        options:
          - framework-dependent
          - self-contained
          - nupkg
          - zip

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnetcore-version }}
      
      # Step 3a: Validate Solution File
      - name: Validate Solution File
        id: validate-solution
        run: |
          if [ ! -f "${{ inputs.solution_path }}" ]; then
            echo "Error: Solution file not found at ${{ inputs.solution_path }}"
            echo "sln_exists=false" >> $GITHUB_ENV
          else
            echo "sln_exists=true" >> $GITHUB_ENV
            echo "solution_file=$(ls *.sln | head -n 1)"
          fi

      # Step 3b: Validate Runtime
      - name: Validate Runtime
        if: ${{ inputs.packaging_type == 'self-contained' && !contains('linux-x64 win-x64 osx-x64', inputs.runtime) }}
        run: |
          echo "Invalid runtime specified for self-contained deployment: ${{ inputs.runtime }}"
          exit 1
        

      # Step 4: Detect Project Type
      - name: Detect Project Type
        id: detect-project
        run: |
          if grep -q "<OutputType>Exe</OutputType>" **/*.csproj; then
            echo "project_type=app" >> $GITHUB_OUTPUT
          else
            echo "project_type=library" >> $GITHUB_OUTPUT
          fi

      # Step 5: Restore dependencies
      - name: Restore Dependencies for Solution
        if: env.sln_exists == 'true' 
        run: dotnet restore ${{ inputs.solution_path }}

      - name: Restore Dependencies for Projects Individually
        if: env.sln_exists == 'false' 
        run: |
          for project in $(find . -name '*.csproj'); do
            echo "Restoring dependencies for $project..."
            dotnet restore "$project"
          done

      # Step 6: Build Solution
      - name: Build Solution
        if: env.sln_exists == 'true'
        run: dotnet build ${{ inputs.solution_path }} -c ${{ inputs.build_configuration }} --no-restore

      - name: Build Projects Individually
        if: env.sln_exists == 'false'
        run: |
          for project in $(find . -name '*.csproj'); do
            echo "Building $project..."
            dotnet build "$project" -c ${{ inputs.build_configuration }} 
          done

      # Step 7: Run Tests and Collect Code Coverage
      - name: Run Tests with Coverage for Solution
        if: env.sln_exists == 'true'
        run: |
          dotnet test ${{ inputs.solution_path }} -c ${{ inputs.build_configuration }} \
          --collect:"XPlat Code Coverage" \
          /p:CoverletOutput=TestResults/coverage.opencover.xml \
          /p:CoverletOutputFormat=opencover \
          --logger "trx;LogFileName=TestResults/test_results.trx"

      - name: Run Tests with Coverage for Projects Individually
        if: env.sln_exists == 'false'
        run: |
          for project in $(find . -name '*.Tests.csproj'); do
              # if grep -q "<IsTestProject>true</IsTestProject>" "$project"; then
            echo "Running tests for $project..."
            dotnet test "$project" -c ${{ inputs.build_configuration }} \
              --logger "trx;LogFileName=$(basename $project .csproj)-test-results.trx" \
              --collect:"XPlat Code Coverage"
              # fi
          done

      # Step 8: Package for Applications
      - name: Package Application for solution
        if: ${{ steps.detect-project.outputs.project_type == 'app' && env.sln_exists == 'true' }}
        run: |
          case ${{ inputs.packaging_type }} in
            framework-dependent)
              dotnet publish ${{ inputs.solution_path }} -c ${{ inputs.build_configuration }} -o publish
              ;;
            self-contained)
              dotnet publish ${{ inputs.solution_path }} -c ${{ inputs.build_configuration }} --self-contained -r ${{ inputs.runtime }} -o publish
              ;;
            zip)
              dotnet publish ${{ inputs.solution_path }} -c ${{ inputs.build_configuration }} -o publish
              zip -r app-package.zip publish
              ;;
          esac
        shell: bash

      - name: Package Applications for Projects Individually
        if: ${{ steps.detect-project.outputs.project_type == 'app' && env.sln_exists == 'false' }}
        run: |
          for project in $(find . -name '*.csproj'); do
            echo "Packaging application $project..."
            case ${{ inputs.packaging_type }} in
              framework-dependent)
                dotnet publish "$project" -c ${{ inputs.build_configuration }} -o ./publish/$(basename "$project" .csproj)
                ;;
              self-contained)
                dotnet publish "$project" -c ${{ inputs.build_configuration }} --self-contained -r ${{ inputs.runtime }} -o ./publish/$(basename "$project" .csproj)
                ;;
              zip)
                dotnet publish "$project" -c ${{ inputs.build_configuration }} -o ./publish/$(basename "$project" .csproj)
                zip -r $(basename "$project" .csproj)-package.zip ./publish/$(basename "$project" .csproj)
                ;;
            esac
          done

      # Step 9: Package for Libraries
      - name: Package Library for Solution
        if: ${{ steps.detect-project.outputs.project_type == 'library' && env.sln_exists == 'true' }}
        run: |
          case ${{ inputs.packaging_type }} in
            nupkg)
              dotnet pack ${{ inputs.solution_path }} -c ${{ inputs.build_configuration }} --no-build
              ;;
            zip)
              dotnet pack ${{ inputs.solution_path }} -c ${{ inputs.build_configuration }} --no-build
              zip -r library-package.zip ./bin/${{ inputs.build_configuration }}
              ;;
          esac
        shell: bash

      - name: Package Libraries for Projects Individually
        if: ${{ steps.detect-project.outputs.project_type == 'library' && env.sln_exists == 'false' }}
        run: |
          for project in $(find . -name '*.csproj'); do
            echo "Packaging library $project..."
            case ${{ inputs.packaging_type }} in
              nupkg)
                dotnet pack "$project" -c ${{ inputs.build_configuration }} --no-build
                ;;
              zip)
                dotnet pack "$project" -c ${{ inputs.build_configuration }} --no-build
                zip -r $(basename "$project" .csproj)-library.zip ./bin/${{ inputs.build_configuration }}
                ;;
            esac
          done

      # Step 10: Upload Build Artifacts
      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build-artifacts
      #     path: |
      #       publish/
      #       app-package.zip
      #       library-package.zip
      #       ./bin/${{ inputs.build_configuration }}/*.nupkg

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ./publish/
            ./*.zip
            ./bin/${{ inputs.build_configuration }}/*.nupkg

      # - name: Prepare Artifacts
      #   run: |
      #     mkdir -p artifacts/code-coverage artifacts/test-results
      #     find . -name '*.trx' -exec cp {} artifacts/test-results/ \;
      #     find . -name 'coverage.cobertura.xml' -exec cp {} artifacts/code-coverage/ \;

      # Step 11: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults

      # # Step 12: Upload Code Coverage
      # - name: Upload Code Coverage
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: code-coverage
      #     path: TestResults/

      # Step 5: Generate Coverage Report (HTML)
      # - name: Generate Coverage Report
      #   run: |
      #     dotnet tool install --global dotnet-reportgenerator-globaltool
      #     reportgenerator -reports:**/TestResults/**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html

      # Step 6: Upload Coverage Report as Artifact
      # - name: Upload Coverage Report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: code-coverage-report
      #     path: |
      #       **/TestResults/**/coverage.cobertura.xml

