name: Generate Workflow

on:
  workflow_dispatch:

# permissions:
#   contents: write
#   packages: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pyyaml jinja2 PyGithub

      - name: Debug GITHUB_TOKEN Permissions
        run: |
          echo "Checking GITHUB_TOKEN permissions..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/collaborators
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}
          
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.MYPAT }}
        run: python scripts/generate_workflow.py

  trigger-dynamic:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Trigger Dynamic Workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/dynamic-workflow.yml/dispatches \
          -d '{"ref":"main"}'
