name: Retrieve Repositories Contributed To

on:
  workflow_dispatch: # Trigger the workflow manually

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          echo "GITHUB_GRAPHQL_API=https://api.github.com/graphql" >> $GITHUB_ENV

      - name: Query GitHub GraphQL API
        env:
          GITHUB_TOKEN: ${{ secrets.MYPAT }}
        run: |
          # Prepare the query
          QUERY='{
            "query": "query {
              organization(login: \"kcalls\") {
                repositories(first: 10) {
                  edges {
                    node {
                      name
                      description
                      isPrivate
                      url
                      createdAt
                      collaborators(first: 10) {
                        edges {
                          node {
                            login
                          }
                        }
                      }
                    }
                  }
                }
              }
            }"
          }'

          # Execute the query using curl
          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "$QUERY" \
            $GITHUB_GRAPHQL_API)

          # Validate and output the response
          echo "GraphQL Response:"
          echo $RESPONSE

      - name: Save output for debugging
        run: |
          echo "$RESPONSE" > graphql_response.json
          cat graphql_response.json
